---
apiVersion: v1
kind: Workload
metadata:
  name: amedeo-tf-04
spec:
  driver: pwm.docker
  selectors:
    node:
      name: emcprom09
    cpu:
      product_name: pwm.all
  image: 
    image: ubuntu
  config: 
    cmd: /bin/bash
  volumes:
    - name: home
      storage: pwmzfs01
      target: /home
  #plugins:
  #  telegram:
  #    id: 183130772
  #    sendOn:
  #      - exited
  #      - crashed
  #      - running      
