---
apiVersion: v1
kind: Workload
metadata:
  name: amedeo-18
spec:
  driver: pwm/nvidia-docker
  selectors:
    cpu:
      product_name: Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
  image: 
    image: ubuntu
  config: 
    cmd: /bin/bash
