---
apiVersion: v1
kind: GPUWorkload
metadata:
  name: testamedeo-1
  group: prom-lab
spec:
  selectors:
    gpu:
      product_name: Dummy GPU
      count: 1
    node:
      name: dummy-01
  image: 
    registry: registry.promfacility.eu
    image: testamedeo

---
apiVersion: v1
kind: GPUWorkload
metadata:
  name: testamedeo-2
  group: prom-lab
spec:
  selectors:
    gpu:
      product_name: Dummy GPU
      count: 2
    node:
      name: dummy-03
  image: 
    registry: registry.promfacility.eu
    image: testamedeo


---
apiVersion: v1
kind: GPUWorkload
metadata:
  name: testamedeo-3
  group: prom-lab
spec:
  selectors:
    gpu:
      product_name: Dummy GPU
      count: 3
    node:
      name: dummy-01
  image: 
    registry: registry.promfacility.eu
    image: testamedeo


---
apiVersion: v1
kind: GPUWorkload
metadata:
  name: testamedeo-4
  group: prom-lab
spec:
  selectors:
    gpu:
      product_name: Dummy GPU
      count: 1
    node:
      name: dummy-02
  image: 
    registry: registry.promfacility.eu
    image: testamedeo

---
apiVersion: v1
kind: GPUWorkload
metadata:
  name: testamedeo-5
  group: prom-lab
spec:
  selectors:
    gpu:
      product_name: Dummy GPU
      count: 1
    node:
      name: dummy-02
  image: 
    registry: registry.promfacility.eu
    image: testamedeo


---
apiVersion: v1
kind: GPUWorkload
metadata:
  name: testamedeo-6
  group: prom-lab
spec:
  selectors:
    gpu:
      product_name: Dummy GPU
      count: 1
    node:
      name: dummy-01
  image: 
    registry: registry.promfacility.eu
    image: testamedeo

---
apiVersion: v1
kind: GPUWorkload
metadata:
  name: testamedeo-7
  group: prom-lab
spec:
  selectors:
    gpu:
      product_name: Dummy GPU
      count: 1
  image: 
    registry: registry.promfacility.eu
    image: testamedeo


---
apiVersion: v1
kind: GPUWorkload
metadata:
  name: testamedeo-8
  group: prom-lab
spec:
  selectors:
    gpu:
      product_name: Dummy GPU
      count: 3
    node:
      name: dummy-01
  image: 
    registry: registry.promfacility.eu
    image: testamedeo


---
apiVersion: v1
kind: GPUWorkload
metadata:
  name: testamedeo-9
  group: prom-lab
spec:
  selectors:
    gpu:
      product_name: Dummy GPU
      count: 1
    node:
      name: dummy-02
  image: 
    registry: registry.promfacility.eu
    image: testamedeo

---
apiVersion: v1
kind: GPUWorkload
metadata:
  name: testamedeo-10
  group: prom-lab
spec:
  selectors:
    gpu:
      product_name: Dummy GPU
      count: 1
    node:
      name: dummy-02
  image: 
    registry: registry.promfacility.eu
    image: testamedeo