#---
#apiVersion: v1
#kind: Workload
#metadata:
#  name: amedeo-ts-2
#  group: prom-lab
#spec:
#  driver: pwm.nvidia-docker
#  selectors:
#    cpu:
#      product_name:  Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
#      count: 1
#  image: 
#    image: ubuntu
#  volumes:
#    - name: myvol
#      storage: pwmzfs01
#      #path: /example
#      target: /home
#  config:
#    startMode: -itd
#    cmd: /bin/bash

---
apiVersion: v1
kind: Workload
metadata:
  name: amedeo-lambda-1
  group: prom-lab
spec:
  driver: pwm.nvidia-docker
  selectors:
    gpu:
      product_name: Quadro RTX 6000
      count: 1
  image: 
    image: ubuntu
  volumes:
    - name: amedeo-vol
      storage: pwmzfs01
      target: /home
  config:
    cmd: /bin/bash

---
apiVersion: v1
kind: Workload
metadata:
  name: amedeo-lambda-2
  group: prom-lab
spec:
  driver: pwm.nvidia-docker
  selectors:
    gpu:
      product_name: GeForce GTX 1080 Ti
      count: 1
  image: 
    image: ubuntu
  volumes:
    - name: amedeo-vol
      storage: pwmzfs01
      target: /home
  config:
    cmd: /bin/bash

---
apiVersion: v1
kind: Workload
metadata:
  name: amedeo-lambda-3
  group: prom-lab
spec:
  driver: pwm.nvidia-docker
  selectors:
    gpu:
      product_name: Quadro RTX 6000
      count: 1
  image: 
    image: ubuntu
  volumes:
    - name: amedeo-vol
      storage: pwmzfs01
      target: /home
  config:
    cmd: /bin/bash
    cpus: 12